# prettier-ignore
apiVersion: 3
name: royco-vault-pipeline
status: ACTIVE
resource_size: s
sources:
  raw_market_vault_reference:
    name: raw_market_vault
    subgraphs:
      {{#metadata}}
      - name: royco-vault-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_market_token_balance_vault_reference:
    name: raw_market_token_balance_vault
    subgraphs:
      {{#metadata}}
      - name: royco-vault-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_offer_vault_reference:
    name: raw_offer_vault
    subgraphs:
      {{#metadata}}
      - name: royco-vault-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_offer_token_balance_vault_reference:
    name: raw_offer_token_balance_vault
    subgraphs:
      {{#metadata}}
      - name: royco-vault-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_position_vault_reference:
    name: raw_position_vault
    subgraphs:
      {{#metadata}}
      - name: royco-vault-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_position_token_balance_vault_reference:
    name: raw_position_token_balance_vault
    subgraphs:
      {{#metadata}}
      - name: royco-vault-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_volume_reference:
    name: raw_volume
    subgraphs:
      {{#metadata}}
      - name: royco-vault-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
transforms: {}
sinks:
  raw_market_vault_postgres:
    type: postgres
    table: raw_market_vault
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_market_vault"
    from: raw_market_vault_reference
  raw_market_token_balance_vault_postgres:
    type: postgres
    table: raw_market_token_balance_vault
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_market_token_balance_vault"
    from: raw_market_token_balance_vault_reference
  raw_offer_vault_postgres:
    type: postgres
    table: raw_offer_vault
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_offer_vault"
    from: raw_offer_vault_reference
  raw_offer_token_balance_vault_postgres:
    type: postgres
    table: raw_offer_token_balance_vault
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_offer_token_balance_vault"
    from: raw_offer_token_balance_vault_reference
  raw_position_vault_postgres:
    type: postgres
    table: raw_position_vault
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_position_vault"
    from: raw_position_vault_reference
  raw_position_token_balance_vault_postgres:
    type: postgres
    table: raw_position_token_balance_vault
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_position_token_balance_vault"
    from: raw_position_token_balance_vault_reference
  raw_volume_postgres:
    type: postgres
    table: raw_volume
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_volume"
    from: raw_volume_reference