# prettier-ignore
apiVersion: 3
name: royco-recipe-pipeline
status: ACTIVE
resource_size: s
sources:
  raw_market_recipe_reference:
    name: raw_market_recipe
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_market_token_balance_recipe_reference:
    name: raw_market_token_balance_recipe
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_offer_recipe_reference:
    name: raw_offer_recipe
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_offer_token_balance_recipe_reference:
    name: raw_offer_token_balance_recipe
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_position_recipe_reference:
    name: raw_position_recipe
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_position_token_balance_recipe_reference:
    name: raw_position_token_balance_recipe
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_volume_reference:
    name: raw_volume
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  raw_global_activity_reference:
    name: raw_global_activity
    subgraphs:
      {{#metadata}}
      - name: royco-recipe-{{network}}
        version: {{version}}
      {{/metadata}}
transforms: {}
sinks:
  raw_market_recipe_postgres:
    type: postgres
    table: raw_market_recipe
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_market_recipe"
    from: raw_market_recipe_reference
  raw_market_token_balance_recipe_postgres:
    type: postgres
    table: raw_market_token_balance_recipe
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_market_token_balance_recipe"
    from: raw_market_token_balance_recipe_reference
  raw_offer_recipe_postgres:
    type: postgres
    table: raw_offer_recipe
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_offer_recipe"
    from: raw_offer_recipe_reference
  raw_offer_token_balance_recipe_postgres:
    type: postgres
    table: raw_offer_token_balance_recipe
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_offer_token_balance_recipe"
    from: raw_offer_token_balance_recipe_reference
  raw_position_recipe_postgres:
    type: postgres
    table: raw_position_recipe
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_position_recipe"
    from: raw_position_recipe_reference
  raw_position_token_balance_recipe_postgres:
    type: postgres
    table: raw_position_token_balance_recipe
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_position_token_balance_recipe"
    from: raw_position_token_balance_recipe_reference
  raw_volume_postgres:
    type: postgres
    table: raw_volume
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_volume"
    from: raw_volume_reference
  raw_global_activity_postgres:
    type: postgres
    table: raw_global_activity
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: raw_global_activity"

