// Static string constants shared across handlers.
//
// These strings land in Postgres columns and are queried by downstream
// dashboards, so treat every value here as part of the public contract — adding
// is cheap, changing is a data migration. See CLAUDE.md §9.
//
// Chain-specific values (CHAIN_ID, VAULT_MAJOR_TYPE) live in ./static.ts, which
// is GENERATED by `npm run prepare:markets:<network>` from
// config/markets/constants.template.ts. Do not edit static.ts.

// === GLOBAL ===
export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

// === UPDATE TYPES ===
export const UPDATE_TYPE_MULTIPLIER = "multiplier";
export const UPDATE_TYPE_OVERRIDE = "override";

// === TRANSFER CATEGORIES ===
// GlobalTokenTransfer.category / GlobalTokenActivity.category
export const CATEGORY_ASSETS = "assets";
export const CATEGORY_SHARES = "shares";

// === TRANSFER SUB CATEGORIES ===
// GlobalTokenTransfer.subCategory / GlobalTokenActivity.subCategory
export const SUB_CATEGORY_MINT = "mint";
export const SUB_CATEGORY_BURN = "burn";
export const SUB_CATEGORY_TRANSFER = "transfer";
export const SUB_CATEGORY_TRANSFER_IN = "transferIn";
export const SUB_CATEGORY_TRANSFER_OUT = "transferOut";
export const SUB_CATEGORY_DEPOSIT = "deposit";
export const SUB_CATEGORY_WITHDRAW = "withdraw";

// === ACTIVITY TYPES ===
// GlobalTokenActivity.type
export const ACTIVITY_TYPE_TRANSFER = "transfer";

// === STATUSES ===
// GlobalTokenActivity.status. Day has no async request lifecycle (unlike
// royco-rwa's AsyncVault), so a token activity is only ever "completed".
export const STATUS_COMPLETED = "completed";

// === TRANCHE TYPES ===
// DayVaultState.minorType / DayVaultStateHistorical.minorType.
//
// These also correspond to the on-chain `TrancheType` enum accepted by
// RoycoDayKernel.previewSyncTrancheAccounting(uint8). Do NOT hardcode the
// numeric value — read it from the tranche's own TRANCHE_TYPE() view. The ABI
// carries no enum names, so the ordering below is a naming convention only, not
// a claim about the on-chain enum. See CLAUDE.md §6.
export const TRANCHE_TYPE_SENIOR = "senior";
export const TRANCHE_TYPE_JUNIOR = "junior";
export const TRANCHE_TYPE_LIQUIDITY = "liquidity";

// === FEES ===
// DayFeeState.majorType — the fee's source. Part of the entity id, because a
// single (vault, account) pair can accrue from more than one source: Senior
// emits BOTH ProtocolFeeSharesMinted and LiquidityPremiumSharesMinted.
export const FEES_MAJOR_TYPE_PROTOCOL = "protocol";
export const FEES_MAJOR_TYPE_LIQUIDITY_PREMIUM = "liquidityPremium";

// === FEES MINOR TYPES ===
// DayFeeState.minorType — the unit the fee is denominated in.
export const FEES_MINOR_TYPE_SHARES = "shares";
export const FEES_MINOR_TYPE_ASSETS = "assets";
