// Static string constants shared across handlers.
//
// These strings land in Postgres columns and are queried by downstream
// dashboards, so treat every value here as part of the public contract — adding
// is cheap, changing is a data migration. See CLAUDE.md §9.
//
// Chain-specific values (CHAIN_ID, VAULT_MAJOR_TYPE) live in ./static.ts, which
// is GENERATED by `npm run prepare:markets:<network>` from
// config/markets/constants.template.ts. Do not edit static.ts.

// === GLOBAL ===
export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

/** Sentinel for an unavailable optional ERC20 decimals view. */
export const ERC20_DECIMALS_UNKNOWN: i32 = 0;

/** Sentinel for an unavailable optional ERC20 symbol view. */
export const ERC20_SYMBOL_UNKNOWN = "";

// === UPDATE TYPES ===
export const UPDATE_TYPE_MULTIPLIER = "multiplier";
export const UPDATE_TYPE_OVERRIDE = "override";

// === TRANSFER CATEGORIES ===
// GlobalTokenTransfer.category / GlobalTokenActivity.category
export const CATEGORY_ASSETS = "assets";
export const CATEGORY_SHARES = "shares";

// === TRANSFER SUB CATEGORIES ===
// GlobalTokenTransfer.subCategory / GlobalTokenActivity.subCategory
export const SUB_CATEGORY_MINT = "mint";
export const SUB_CATEGORY_BURN = "burn";
export const SUB_CATEGORY_TRANSFER = "transfer";
export const SUB_CATEGORY_TRANSFER_IN = "transferIn";
export const SUB_CATEGORY_TRANSFER_OUT = "transferOut";
export const SUB_CATEGORY_DEPOSIT = "deposit";
export const SUB_CATEGORY_WITHDRAW = "withdraw";

// === MARKET STATES ===
// DayMarketState.marketState.
//
// The on-chain enum is `MarketState { PERPETUAL, FIXED_TERM }`
// (contracts/libraries/Types.sol), so 0 is PERPETUAL. That reads backwards to
// anyone who assumes "fixed" comes first, and it was wrong across this repo's
// docs and fixtures until it was checked against the source. The ABI cannot tell
// you — it carries the enum's TYPE name but none of its member names (§4).
export const MARKET_STATE_PERPETUAL = "perpetual"; // enum 0
export const MARKET_STATE_FIXED = "fixed"; // enum 1

// === TOKEN INDICES ===
// The trailing discriminator on GlobalTokenTransfer.id and GlobalTokenActivity.id.
// One log can move several tokens, so the index identifies WHICH leg a row is.
//
// These are POSITIONAL and fixed per leg — never a running counter over the
// non-zero legs. A counter makes tokenIndex 1 mean "junior assets" in one row and
// "liquidity assets" in another, and the leg is then unrecoverable from Neon:
// tokenAddress is the only other clue, and the shipped identical-ST/JT kernel
// gives the senior and junior legs the SAME asset token.
export const TOKEN_INDEX_SINGLE: i32 = 0; // logs that move exactly one token
// TWO legs in v2, not three: AssetClaims merged its separate senior and junior asset
// legs into one `collateralAssets`. The indices stay POSITIONAL — index 0 is always the
// collateral leg and 1 always the liquidity leg, even when one amount is zero.
export const REDEEM_TOKEN_INDEX_COLLATERAL_ASSETS: i32 = 0;
export const REDEEM_TOKEN_INDEX_LIQUIDITY_TRANCHE_ASSETS: i32 = 1;

// === ACTIVITY TYPES ===
// GlobalTokenActivity.type
export const ACTIVITY_TYPE_TRANSFER = "transfer";

// === STATUSES ===
// GlobalTokenActivity.status. Day has no async request lifecycle (unlike
// royco-rwa's AsyncVault), so a token activity is only ever "completed".
export const STATUS_COMPLETED = "completed";

// === SYNC TYPES ===
// DayTrancheAccountingSyncedHistory.syncType — which of the kernel's two sync events a
// collapsed row last settled on. A block's row starts as "preOp" and is overwritten to
// "postOp" if an operation settles in the same block.
export const SYNC_TYPE_PRE_OP = "preOp";
export const SYNC_TYPE_POST_OP = "postOp";

// === OPERATIONS ===
// DayTrancheAccountingSyncedHistory.operation, from
// PostOpTrancheAccountingSynced's `op` (uint8 enum -> i32).
//
// Order is the on-chain `Operation` enum's declaration order
// (contracts/libraries/Types.sol) — six members in the deployed contracts. The ABI
// carries the enum's TYPE name but none of its member names, so this ordering comes
// from the source and is not guessable (§4). Multi-asset LPT flows use the plain LPT
// operation values. Re-read
// Types.sol whenever contracts/ changes; the ABI, build, and tests cannot reveal drift.
//
export const OPERATION_ST_DEPOSIT = "stDeposit"; // enum 0
export const OPERATION_ST_REDEEM = "stRedeem"; // enum 1
export const OPERATION_JT_DEPOSIT = "jtDeposit"; // enum 2
export const OPERATION_JT_REDEEM = "jtRedeem"; // enum 3
export const OPERATION_LPT_DEPOSIT = "lptDeposit"; // enum 4
export const OPERATION_LPT_REDEEM = "lptRedeem"; // enum 5
// An out-of-range ordinal means the enum grew and this list did not — surfaced as
// "unknown" rather than silently mapped to a neighbour.
export const OPERATION_UNKNOWN = "unknown";

// === TRANCHE TYPES ===
// DayVaultState.minorType / DayVaultStateHistorical.minorType.
//
// These also correspond to the on-chain `TrancheType` enum accepted by
// RoycoDayKernel.previewSyncTrancheAccountingFor(uint8). Do NOT hardcode the
// numeric value — read it from the tranche's own TRANCHE_TYPE() view. The ABI
// carries no enum names, so the ordering below is a naming convention only, not
// a claim about the on-chain enum. See CLAUDE.md §6.
export const TRANCHE_TYPE_SENIOR = "senior";
export const TRANCHE_TYPE_JUNIOR = "junior";
export const TRANCHE_TYPE_LIQUIDITY = "liquidity";

// === FEES ===
// DayFeeState needs NO fee-specific constants. The only fee is the protocol fee,
// always minted as shares, so its majorType/minorType mirror DayVaultState:
//   majorType = VAULT_MAJOR_TYPE  ("day")            — the product
//   minorType = the vault's own minorType (TRANCHE_TYPE_SENIOR/JUNIOR/LIQUIDITY)
// The handler reads both off the loaded DayVaultState; nothing to define here.
//
// The LIQUIDITY PREMIUM is NOT a fee — it is minted into the market's own
// accounting, not taken from a holder — so it has no DayFeeState row at all. It
// lives in DayLiquidityPremiumSharesMintedHistory (a RECORDS entity). The old
// "protocol"/"liquidityPremium" majorType and "shares"/"assets" minorType
// constants were removed with that reclassification.
