# prettier-ignore
apiVersion: 3
name: royco-metaverse-pipeline
status: ACTIVE
resource_size: s
sources:
  royco_metaverse_reference:
    name: royco_metaverse
    subgraphs:
      {{#metadata}}
      - name: royco-metaverse-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
transforms: {}
sinks:
  royco_metaverse_postgres:
    type: postgres
    table: royco_metaverse
    schema: public
    secret_name: NEON_ROYCO
    description: "Postgres sink for: royco_metaverse"
    from: royco_metaverse_reference
