specVersion: 1.3.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: RoycoAccountFactory
    network: {{network}}
    source:
      address: "{{roycoAccountFactoryAddress}}"
      abi: RoycoAccountFactory
      startBlock: {{roycoAccountFactoryStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - RoycoAccountDeployed
        - RawSafe
        - RawSafeMap
      abis:
        - name: RoycoAccountFactory
          file: ./abis/RoycoAccountFactory.json
        - name: ISafe
          file: ./abis/ISafe.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: RoycoAccountDeployed(indexed address,uint96,address)
          handler: handleRoycoAccountDeployed
      file: ./src/royco-account-factory.ts
  - kind: ethereum
    name: ERC20
    network: {{network}}
    source:
      abi: ERC20
      startBlock: {{roycoAccountFactoryStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - RawSafeTokenizedPosition
      abis:
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./src/erc20.ts
templates:
  - name: SafeTemplate
    kind: ethereum/contract
    network: {{network}}
    source:
      abi: ISafe
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - SafeSetup
        - ExecutionSuccess
        - ExecutionFailure
        - RawSafe
        - RawSafeMap
        - RawSafeTokenizedPosition
      abis:
        - name: ISafe
          file: ./abis/ISafe.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: SafeSetup(indexed address,address[],uint256,address,address)
          handler: handleSafeSetup
        - event: ExecutionSuccess(indexed bytes32,uint256)
          handler: handleExecutionSuccess
        - event: ExecutionFailure(indexed bytes32,uint256)
          handler: handleExecutionFailure
        - event: AddedOwner(indexed address)
          handler: handleAddedOwner
        - event: RemovedOwner(indexed address)
          handler: handleRemovedOwner
        - event: ChangedThreshold(uint256)
          handler: handleChangedThreshold
      file: ./src/safe.ts