# prettier-ignore
specVersion: 1.3.0
schema:
  file: ./schema.graphql
dataSources:
{{#asyncVaults}}
  - kind: ethereum
    name: Vault{{id}}
    network: {{network}}
    source:
      address: "{{vaultAddress}}"
      abi: AsyncVaultConcrete
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - Transfer
        - Deposit
        - Withdraw
        - QueuedWithdrawal
        - RequestCancelled
        - RequestMovedToNextEpoch
        - EpochClosed
        - EpochProcessed
        - RequestClaimed
        - RoleGranted
      abis:
        - name: BaseVault
          file: ./abis/BaseVault.json
        - name: AsyncVaultConcrete
          file: ./abis/AsyncVaultConcrete.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
          receipt: true
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
          receipt: true
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
          receipt: true
        - event: QueuedWithdrawal(indexed address,indexed address,indexed address,uint256,uint256,uint256)
          handler: handleQueuedWithdrawal
          receipt: true
        - event: RequestCancelled(indexed address,uint256,uint256)
          handler: handleRequestCancelled
          receipt: true
        - event: RequestMovedToNextEpoch(indexed address,uint256,uint256,uint256)
          handler: handleRequestMovedToNextEpoch
          receipt: true
        - event: EpochClosed(uint256)
          handler: handleEpochClosed
          receipt: true
        - event: EpochProcessed(uint256,uint256,uint256,uint256)
          handler: handleEpochProcessed
          receipt: true
        - event: RequestClaimed(indexed address,uint256,uint256[])
          handler: handleRequestClaimed
          receipt: true
        - event: RoleGranted(indexed bytes32,indexed address,indexed address)
          handler: handleRoleGranted
          receipt: true
        - event: ManagementFeeAccrued(indexed address,uint256,uint256)
          handler: handleManagementFeeAccrued
          receipt: true
        - event: PerformanceFeeAccrued(indexed address,uint256,uint256)
          handler: handlePerformanceFeeAccrued
          receipt: true
      file: ./src/concrete-async-vault.ts
{{/asyncVaults}}
{{#standardVaults}}
  - kind: ethereum
    name: Vault{{id}}
    network: {{network}}
    source:
      address: "{{vaultAddress}}"
      abi: BaseVault
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - Transfer
        - Deposit
        - Withdraw
      abis:
        - name: BaseVault
          file: ./abis/BaseVault.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
          receipt: true
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
          receipt: true
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
          receipt: true
      file: ./src/vault.ts
{{/standardVaults}}
