# prettier-ignore
specVersion: 1.3.0
schema:
  file: ./schema.graphql
dataSources:
{{#entryPoints}}
  - kind: ethereum
    name: Vault{{id}}
    network: {{network}}
    source:
      address: "{{address}}"
      abi: RoycoEntryPoint
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - DepositRequested
        - DepositExecuted
        - DepositRequestCancelled
        - RedemptionRequested
        - RedemptionExecuted
        - RedemptionRequestCancelled
        - ProtocolFeeSharesAccrued
        - TrancheConfigUpdated
      abis:
        - name: RoycoEntryPoint
          file: ./abis/RoycoEntryPoint.json
        - name: BaseVault
          file: ./abis/BaseVault.json
      eventHandlers:
        - event: DepositRequested(indexed address,indexed uint256,indexed address,uint256,uint32,uint64)
          handler: handleDepositRequested
          receipt: true
        - event: DepositExecuted(indexed address,indexed uint256,indexed address,uint256,uint256,uint256)
          handler: handleDepositExecuted
          receipt: true
        - event: DepositRequestCancelled(indexed address,indexed uint256,address,uint256)
          handler: handleDepositRequestCancelled
          receipt: true
        - event: RedemptionRequested(indexed address,indexed uint256,indexed address,uint256,uint32,uint64)
          handler: handleRedemptionRequested
          receipt: true
        - event: RedemptionExecuted(indexed address,indexed uint256,indexed address,uint256,uint256,(uint256,uint256,uint256),(uint256,uint256,uint256))
          handler: handleRedemptionExecuted
          receipt: true
        - event: RedemptionRequestCancelled(indexed address,indexed uint256,address,uint256)
          handler: handleRedemptionRequestCancelled
          receipt: true
        - event: ProtocolFeeSharesAccrued(indexed address,uint256)
          handler: handleProtocolFeeSharesAccrued
          receipt: true
        - event: TrancheConfigUpdated(indexed address,(bool,uint8,uint24,uint24))
          handler: handleTrancheConfigUpdated
          receipt: true
      file: ./src/royco-entrypoint.ts
{{/entryPoints}}
